# Generated by Django 3.0.6 on 2020-06-29 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('framework', '0002_auto_20200628_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='vote',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
