# Generated by Django 3.0.6 on 2020-06-26 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('framework', '0002_auto_20200626_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='vote',
        ),
        migrations.AddField(
            model_name='framework',
            name='vote',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
