# Generated by Django 3.0.6 on 2020-06-26 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('framework', '0003_auto_20200626_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='vote',
        ),
        migrations.AddField(
            model_name='framework',
            name='vote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
