# Generated by Django 3.0.6 on 2020-06-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_auto_20200626_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
