# Generated by Django 3.0.6 on 2020-07-05 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('framework', '0004_auto_20200705_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='vote',
        ),
        migrations.AddField(
            model_name='framework',
            name='vote',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
